name: CustomEnchantments
main: xyz.acrylicstyle.customenchantments.CustomEnchantmentsPlugin
version: "1.0.0"
api-version: "1.20"
commands:
  customenchantments:
    aliases: ["ce", "customenchant"]
    permission: customenchantments.command
